"""empty message

Revision ID: 2dbadf615030
Revises: c0e6685dd2ac
Create Date: 2026-05-07 21:27:58.173690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbadf615030'
down_revision = 'c0e6685dd2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favortie_profile',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.drop_table('favourtie_profile')
    with op.batch_alter_table('p_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPublic', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p_profile', schema=None) as batch_op:
        batch_op.drop_column('isPublic')

    op.create_table('favourtie_profile',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('favourtie_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('favorite_id', name=op.f('favourtie_profile_pkey'))
    )
    op.drop_table('favortie_profile')
    # ### end Alembic commands ###
