"""empty message

Revision ID: 6c30670c9d76
Revises: 26dc0bd09550
Create Date: 2026-05-06 13:42:00.373403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c30670c9d76'
down_revision = '26dc0bd09550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat1_id', sa.Integer(), nullable=True),
    sa.Column('chat2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat1_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['chat2_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom_profile.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_profile')
    op.drop_table('chatroom_profile')
    # ### end Alembic commands ###
