"""empty message

Revision ID: f513b8dd347b
Revises: 2dbadf615030
Create Date: 2026-05-07 22:14:34.020940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f513b8dd347b'
down_revision = '2dbadf615030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interest_profile_name'), ['name'], unique=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_longitude'), ['longitude'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_longitude'))
        batch_op.drop_index(batch_op.f('ix_user_profile_latitude'))

    with op.batch_alter_table('interest_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_profile_name'))

    # ### end Alembic commands ###
